site_name: Panlexia
site_url: http://www.pandunia.info/panlexia
repo_url: https://github.com/barumau/panlexia/
docs_dir: generated/
site_dir: ../html/panlexia
use_directory_urls: false
theme: material
nav:
    - Index: 'index.md'
