name: "Checks for changeset"
on: push
jobs:
  check-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip --progress-bar off
          pip install -r requirements.txt --progress-bar off

      - name: Download NLTK dependencies
        run: python src/download_nltk.py

      - name: Find and rename temporary concept ids
        run: python src/check_new_concept_ids.py
